{"timestamp":"2025-08-01T17:04:48.140229","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-08-01T17:04:48.140868","level":"info","event":"Filling up the DagBag from /home/user/airflow/dags/my_first_dag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-08-01T17:04:49.012696Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-01T17:04:49.012816Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-01T17:04:49.012967Z","level":"info","event":"Current task name:create_composite_before","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-01T17:04:49.013009Z","level":"info","event":"Dag name:ndvi_change_detection_pipeline_branching","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-01T17:04:49.027094Z","level":"info","event":"l date li aana  2025-01-04","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-01T17:04:49.033690","level":"info","event":"GDAL signalled an error: err_no=4, msg='2025-01-04_NDVI.tif: No such file or directory'","logger":"rasterio._env"}
{"timestamp":"2025-08-01T17:04:49.033889","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"RasterioIOError","exc_value":"2025-01-04_NDVI.tif: No such file or directory","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/user/airflow_venv_clean/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":877,"name":"run"},{"filename":"/home/user/airflow_venv_clean/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1164,"name":"_execute_task"},{"filename":"/home/user/airflow_venv_clean/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/user/airflow_venv_clean/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":217,"name":"execute"},{"filename":"/home/user/airflow_venv_clean/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":240,"name":"execute_callable"},{"filename":"/home/user/airflow_venv_clean/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/home/user/airflow/ndvi_utils.py","lineno":776,"name":"create_composite_before_wrapper"},{"filename":"/home/user/airflow/ndvi_utils.py","lineno":693,"name":"create_composite_image"},{"filename":"/home/user/airflow_venv_clean/lib/python3.12/site-packages/rasterio/env.py","lineno":463,"name":"wrapper"},{"filename":"/home/user/airflow_venv_clean/lib/python3.12/site-packages/rasterio/__init__.py","lineno":356,"name":"open"},{"filename":"/home/user/airflow/rasterio/_base.pyx","lineno":312,"name":"rasterio._base.DatasetBase.__init__"}],"is_group":false,"exceptions":[]},{"exc_type":"CPLE_OpenFailedError","exc_value":"2025-01-04_NDVI.tif: No such file or directory","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/user/airflow/rasterio/_base.pyx","lineno":310,"name":"rasterio._base.DatasetBase.__init__"},{"filename":"/home/user/airflow/rasterio/_base.pyx","lineno":221,"name":"rasterio._base.open_dataset"},{"filename":"/home/user/airflow/rasterio/_err.pyx","lineno":359,"name":"rasterio._err.exc_wrap_pointer"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-08-01T17:04:49.034667Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-01T17:04:49.034842Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-01T17:04:49.034906Z","level":"info","event":"Task:<Task(PythonOperator): create_composite_before>","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-01T17:04:49.034942Z","level":"info","event":"Failure caused by 2025-01-04_NDVI.tif: No such file or directory","chan":"stdout","logger":"task"}
